### ISSUE TITLE
1.20.2 Support

### ISSUE THREAD

**Issue by TheUnknownCod3r** [malloryhayr/voicechat-interaction-paper#9]
Currently, When running on 1.20.2 the mod does work, however intermittently the following error or similar will be posted to the console when users join. 

```
Task #529441 for voicechat_interaction vv1.3.0+1.20.x generated an exception
    java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getWorld()" because the return value of 
    "org.bukkit.Server.getPlayer(java.util.UUID)" is null
        at voicechat-interaction-paper- 
   v1.3.0+1.20.x.jar//dev.igalaxy.voicechatinteraction.VoiceChatInteractionPlugin.activate(VoiceChatInteractionPlugin.java:106)
        at voicechat-interaction-paper-v1.3.0+1.20.x.jar//dev.igalaxy.voicechatinteraction.VoiceChatInteractionPlugin.lambda$onMicPacket$0(VoiceChatInteractionPlugin.java:98)
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1495)
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482)
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Assume its related to changes made in 1.20.2, so opening an issue report. This wasn't an issue on 1.19

**Comment by Metamogul** [comment]
I've just created a PR (https://github.com/malloryhayr/voicechat-interaction-paper/pull/10) that hopefully fixes the issue. If you're impatient you can go ahead and use the updated repo to build the plugin yourself.

**Comment by wiidotmom** [comment]
Fixed in https://github.com/malloryhayr/voicechat-interaction-paper/pull/10

**Comment by TheUnknownCod3r** [comment]
Beautiful, tysm for the quick fix! I didn’t even think to check the dependencies and such.

**Comment by Metamogul** [comment]
Glad to help out! If you @malloryhayr got some spare time (who ever does, right? :D) might be worth investigating if adding renovate to the project might be worth it. It supports [updating dependencies in `.gradle` and `.gradle.kts` files](https://docs.renovatebot.com/java/) and is [available as free GitHub app](https://github.com/apps/renovate).

**Comment by TheUnknownCod3r** [comment]
Same issue for 1.20.4
